version: '3.2'
services:
  dynamo:
    container_name: humut-dynamo-local
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    networks:
      humut-network:
        ipv4_address: 172.16.2.98
  coordinator:
    container_name: hummut_coordinator
    build: "./coordinator"
    ports:
      - "9000:9000"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - DYNAMO_HOST=http://172.16.2.98:8000
    networks:
      humut-network:
        ipv4_address: 172.16.2.99
#  worker1:
#    container_name: hummut_worker1
#    build: "./worker"
#    ports:
#      - "9001:9000"
#    environment:
#      - COORDINATOR_HOST=http://172.16.2.99:9000
#    networks:
#      humut-network:
#        ipv4_address: 172.16.2.4
#  worker2:
#    container_name: hummut_worker2
#    build: "./worker"
#    ports:
#       - "9002:9000"
#    environment:
#      - COORDINATOR_HOST=http://172.16.2.99:9000
#      - AWS_ACCESS_KEY_ID
#      - AWS_SECRET_ACCESS_KEY
#      - AWS_SESSION_TOKEN
#     networks:
#       humut-network:
#         ipv4_address: 172.16.2.3
networks:
  humut-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.2.0/24